name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USE_BAZEL_VERSION: 7.4.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build \
              --config=ci \
              --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
              //...
      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test \
              --config=ci \
              --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
              //... || echo "Tests failed"
